repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0 # Use the ref you want to point at
    hooks:
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --nosort-keys]
      - id: check-xml
      - id: check-yaml
        args: [--unsafe]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: flake8
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
